### PR TITLE
Translated into Russian 

### PR DESCRIPTION
**Pull request by aquaminer**

### CODE REVIEW

**Comment by aquaminer** [comment]
Please yet not approve, I will notify when finished

**Comment by gordonmhy** [comment]
@opkiler22789 okay!

**Comment by aquaminer** [comment]
@hoyinm14mc You could not explain the 'Initialized' word? I and Google translate shocked

**Comment by aquaminer** [comment]
by the way you can already accept the changes

**Comment by gordonmhy** [comment]
@opkiler22789 'Initialized' means you start something from the very beginning.

**Pull request merged**
